# Generated by Django 5.2 on 2025-04-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(null=True),
        ),
    ]
