# Generated by Django 5.2 on 2025-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TECH', 'Tech'), ('ACADEMIC', 'Academic'), ('COMMUNITY', 'Community'), ('MEDIA', 'Media'), ('CORPORATE', 'Corporate')], max_length=50)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
                ('web_url', models.URLField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(max_length=255)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], max_length=50)),
                ('scope', models.TextField()),
                ('benefits', models.TextField()),
                ('events_supported', models.TextField()),
                ('resources', models.TextField()),
                ('achievements', models.TextField()),
                ('target_audience', models.TextField()),
            ],
        ),
    ]
