# Generated by Django 5.2 on 2025-04-10 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='co_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_lead_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityprofile',
            name='community_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityprofile',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
