# Generated by Django 5.2 on 2025-04-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0002_alter_communityprofile_co_lead_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymember',
            old_name='joined_at',
            new_name='joined_date',
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Innovation_WebApp.communityprofile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('community', 'email')},
        ),
    ]
