# Generated by Django 5.2 on 2025-04-10 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
        ('Innovation_WebApp', '0002_alter_communityprofile_co_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivemember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='executivemember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='executivemember',
            name='name',
        ),
        migrations.AddField(
            model_name='executivemember',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='executive_members', to='Innovation_WebApp.communityprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executivemember',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='executive_positions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executivemember',
            name='position',
            field=models.CharField(choices=[('LEAD', 'Community Lead'), ('CO_LEAD', 'Co-Lead'), ('SECRETARY', 'Secretary')], max_length=10),
        ),
    ]
