# Generated by Django 5.2 on 2025-04-11 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_remove_executivemember_bio_and_more'),
        ('Innovation_WebApp', '0003_rename_joined_at_communitymember_joined_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='executivemember',
            unique_together={('user', 'community')},
        ),
    ]
